/* Auto-generated by the cloud monitor (GitHub Actions). Do not edit by hand. */
window.PBCA_FEED = {
  "app": "PH Business Continuity Advisory",
  "client": "mySMB.com",
  "location": "Makati City, Metro Manila",
  "generated_at": "2026-08-21T02:00:00+08:00",
  "current": {
    "tier": 2,
    "tier_label": "PREPARE",
    "action_needed": true,
    "bottom_line": "Makati: No action needed yet — review contingencies and watch the next bulletin.",
    "headline": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin.",
    "confidence": "MEDIUM",
    "next_update": "Automated hourly; full brief at 12:00 NN (Asia/Manila)",
    "monitoring_degraded": false,
    "degraded_note": "Volcano (PHIVOLCS) and dam levels are not yet in the automated cloud version — confirm those on the official sites if relevant.",
    "outlook_3day": [
      {
        "date": "Aug 21",
        "summary": "Drizzle, 40% chance of rain. Max ~30°C."
      },
      {
        "date": "Aug 22",
        "summary": "Heavy drizzle, 80% chance of rain. Max ~29°C."
      },
      {
        "date": "Aug 23",
        "summary": "Rain showers, 86% chance of rain. Max ~29°C."
      }
    ],
    "weather": "An active tropical cyclone appears in the PAGASA bulletin — check the official bulletin for wind signal levels over Metro Manila. Drizzle in Metro Manila; max ~30°C.",
    "heat_index": {
      "max_c": 35,
      "category": "Extreme Caution",
      "note": "Computed from Open-Meteo temperature and humidity for Metro Manila."
    },
    "flood_risk": {
      "level": "Low",
      "category": "No heavy rain forecast",
      "tier": 1,
      "max_mm_hr": 0.5,
      "total_mm_today": 3,
      "note": "No heavy rain forecast for Metro Manila (Open-Meteo)."
    },
    "flood_official": null,
    "volcanoes": [],
    "seismic_24h": {
      "count": 0,
      "ncr_relevant": false,
      "note": "No M4.0+ earthquakes in the PH region in the last 24h."
    },
    "dams": [],
    "areas_watch": {
      "ok": true,
      "checked": 14,
      "areas": [
        {
          "name": "Quezon City",
          "region": "Metro Manila",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.3,
          "total_mm": 2
        },
        {
          "name": "Manila",
          "region": "Metro Manila",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.5,
          "total_mm": 3
        },
        {
          "name": "Marikina",
          "region": "Metro Manila",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.6,
          "total_mm": 4
        },
        {
          "name": "Pasig",
          "region": "Metro Manila",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.4,
          "total_mm": 3
        },
        {
          "name": "Parañaque / Las Piñas",
          "region": "Metro Manila",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.2,
          "total_mm": 1
        },
        {
          "name": "Caloocan / Valenzuela",
          "region": "Metro Manila",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.2,
          "total_mm": 0
        },
        {
          "name": "Antipolo",
          "region": "Rizal",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.6,
          "total_mm": 3
        },
        {
          "name": "Cainta / Taytay",
          "region": "Rizal",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.6,
          "total_mm": 3
        },
        {
          "name": "Bacoor / Imus",
          "region": "Cavite",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.4,
          "total_mm": 2
        },
        {
          "name": "Dasmariñas",
          "region": "Cavite",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.1,
          "total_mm": 0
        },
        {
          "name": "San Pedro / Biñan",
          "region": "Laguna",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.1,
          "total_mm": 0
        },
        {
          "name": "Santa Rosa / Calamba",
          "region": "Laguna",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0,
          "total_mm": 0
        },
        {
          "name": "Meycauayan / Marilao",
          "region": "Bulacan",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.2,
          "total_mm": 0
        },
        {
          "name": "San Jose del Monte",
          "region": "Bulacan",
          "level": "Low",
          "tier": 1,
          "max_mm_hr": 0.7,
          "total_mm": 3
        }
      ],
      "elevated": [],
      "worst_tier": 1,
      "note": "All 14 watched staff/commute areas show low flood risk (Open-Meteo forecast)."
    },
    "sources": [
      {
        "label": "PAGASA — Tropical Cyclone Bulletin",
        "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
      },
      {
        "label": "PAGASA — Weather / Heat Index",
        "url": "https://www.pagasa.dost.gov.ph/weather/heat-index"
      },
      {
        "label": "PAGASA — Flood / Dam",
        "url": "https://www.pagasa.dost.gov.ph/flood"
      },
      {
        "label": "USGS — Earthquakes",
        "url": "https://earthquake.usgs.gov/earthquakes/map/"
      },
      {
        "label": "PHIVOLCS",
        "url": "https://www.phivolcs.dost.gov.ph/"
      }
    ]
  },
  "notifications": [
    {
      "id": "2026-08-20-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-08-20T12:00:00+08:00",
      "title": "PH hazard brief — Aug 20, 2026 — PREPARE",
      "bottom_line": "Makati: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Aug 20, 2026: Makati: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~35°C (Extreme Caution). Staff/commute areas: all clear. Seismic: 3 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 20: Heavy drizzle, 53% chance of rain. Max ~30°C. Aug 21: Thunderstorms, 83% chance of rain. Max ~30°C. Aug 22: Thunderstorms, 83% chance of rain. Max ~29°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-19-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-08-19T12:00:00+08:00",
      "title": "PH hazard brief — Aug 19, 2026 — PREPARE",
      "bottom_line": "Makati: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Aug 19, 2026: Makati: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~34°C (Extreme Caution). Staff/commute areas: all clear. Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Aug 19: Thunderstorms, 100% chance of rain. Max ~29°C. Aug 20: Drizzle, 71% chance of rain. Max ~29°C. Aug 21: Thunderstorms, 67% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-18-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-18T12:00:00+08:00",
      "title": "PH hazard brief — Aug 18, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 18, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~30°C (Caution). Rainfall/flood: Watch — Heavy (Yellow-equivalent). Staff/commute areas: all clear. Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Aug 18: Thunderstorms, 100% chance of rain. Max ~27°C. Aug 19: Rain showers, 96% chance of rain. Max ~28°C. Aug 20: Thunderstorms, 80% chance of rain. Max ~28°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-17-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-17T12:00:00+08:00",
      "title": "PH hazard brief — Aug 17, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 17, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~31°C (Caution). Staff/commute areas: all clear. Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Aug 17: Thunderstorms, 100% chance of rain. Max ~28°C. Aug 18: Thunderstorms, 100% chance of rain. Max ~26°C. Aug 19: Thunderstorms, 98% chance of rain. Max ~27°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-16-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-16T12:00:00+08:00",
      "title": "PH hazard brief — Aug 16, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 16, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~32°C (Caution). Staff/commute areas: all clear. Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 16: Drizzle, 100% chance of rain. Max ~28°C. Aug 17: Thunderstorms, 99% chance of rain. Max ~28°C. Aug 18: Thunderstorms, 100% chance of rain. Max ~27°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-15-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-15T12:00:00+08:00",
      "title": "PH hazard brief — Aug 15, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 15, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~35°C (Extreme Caution). Staff/commute areas: all clear. Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Aug 15: Rain showers, 77% chance of rain. Max ~30°C. Aug 16: Heavy drizzle, 90% chance of rain. Max ~29°C. Aug 17: Rain showers, 96% chance of rain. Max ~28°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-14-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-14T12:00:00+08:00",
      "title": "PH hazard brief — Aug 14, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 14, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~35°C (Extreme Caution). Rainfall/flood: Watch — Heavy (Yellow-equivalent). Staff/commute areas: all clear. Seismic: 3 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 14: Thunderstorms with hail, 100% chance of rain. Max ~30°C. Aug 15: Heavy drizzle, 84% chance of rain. Max ~29°C. Aug 16: Thunderstorms, 97% chance of rain. Max ~28°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-13-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-13T12:00:00+08:00",
      "title": "PH hazard brief — Aug 13, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 13, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~35°C (Extreme Caution). Staff/commute areas: all clear. Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 13: Thunderstorms, 100% chance of rain. Max ~29°C. Aug 14: Heavy drizzle, 78% chance of rain. Max ~30°C. Aug 15: Rain showers, 75% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-12-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-12T12:00:00+08:00",
      "title": "PH hazard brief — Aug 12, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 12, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~34°C (Extreme Caution). Staff/commute areas: all clear. Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Aug 12: Thunderstorms, 100% chance of rain. Max ~29°C. Aug 13: Thunderstorms, 100% chance of rain. Max ~29°C. Aug 14: Thunderstorms, 86% chance of rain. Max ~29°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-11-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-11T12:00:00+08:00",
      "title": "PH hazard brief — Aug 11, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 11, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~34°C (Extreme Caution). Staff/commute areas: all clear. Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 11: Drizzle, 98% chance of rain. Max ~29°C. Aug 12: Thunderstorms, 94% chance of rain. Max ~29°C. Aug 13: Thunderstorms, 96% chance of rain. Max ~29°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-10-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-10T12:00:00+08:00",
      "title": "PH hazard brief — Aug 10, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 10, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~33°C (Extreme Caution). Staff/commute areas: all clear. Seismic: 5 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 10: Thunderstorms, 100% chance of rain. Max ~28°C. Aug 11: Rain showers, 97% chance of rain. Max ~29°C. Aug 12: Thunderstorms, 87% chance of rain. Max ~29°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-09-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-09T12:00:00+08:00",
      "title": "PH hazard brief — Aug 9, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 9, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~33°C (Caution). Staff/commute areas: all clear. Seismic: 2 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 9: Thunderstorms, 100% chance of rain. Max ~28°C. Aug 10: Rain showers, 100% chance of rain. Max ~28°C. Aug 11: Thunderstorms, 98% chance of rain. Max ~29°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-08-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-08T12:00:00+08:00",
      "title": "PH hazard brief — Aug 8, 2026 — No action",
      "bottom_line": "Makati: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 8, 2026: Makati: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~33°C (Caution). Staff/commute areas: all clear. Seismic: 5 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 8: Thunderstorms, 100% chance of rain. Max ~28°C. Aug 9: Thunderstorms, 100% chance of rain. Max ~28°C. Aug 10: Thunderstorms, 100% chance of rain. Max ~29°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-07-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-08-07T12:00:00+08:00",
      "title": "PH hazard brief — Aug 7, 2026 — PREPARE",
      "bottom_line": "Makati: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Aug 7, 2026: Makati: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "M5 quake ~137 km from Makati — may be felt in NCR. Heat index today ~34°C (Extreme Caution). Staff/commute areas: all clear. Seismic: 1 M4.0+ event(s) in the PH region (last 24h); nearest of note M5 ~137 km from Makati (7 km NW of Cabacao, Philippines). 3-day outlook — Aug 7: Thunderstorms, 100% chance of rain. Max ~29°C. Aug 8: Thunderstorms, 100% chance of rain. Max ~28°C. Aug 9: Thunderstorms, 100% chance of rain. Max ~28°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-06-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-08-06T12:00:00+08:00",
      "title": "PH hazard brief — Aug 6, 2026 — PREPARE",
      "bottom_line": "Makati: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Aug 6, 2026: Makati: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~32°C (Caution). Staff/commute areas: all clear. Seismic: 11 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 6: Thunderstorms, 100% chance of rain. Max ~28°C. Aug 7: Thunderstorms, 100% chance of rain. Max ~28°C. Aug 8: Thunderstorms, 100% chance of rain. Max ~28°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-05-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-08-05T12:00:00+08:00",
      "title": "PH hazard brief — Aug 5, 2026 — PREPARE",
      "bottom_line": "Makati: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Aug 5, 2026: Makati: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~33°C (Caution). Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Aug 5: Thunderstorms, 100% chance of rain. Max ~28°C. Aug 6: Thunderstorms, 92% chance of rain. Max ~29°C. Aug 7: Thunderstorms, 98% chance of rain. Max ~28°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-04-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-08-04T12:00:00+08:00",
      "title": "PH hazard brief — Aug 4, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Aug 4, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~33°C (Caution). Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Aug 4: Rain showers, 100% chance of rain. Max ~29°C. Aug 5: Thunderstorms, 100% chance of rain. Max ~27°C. Aug 6: Rain showers, 94% chance of rain. Max ~29°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-03-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-08-03T12:00:00+08:00",
      "title": "PH hazard brief — Aug 3, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Aug 3, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~34°C (Extreme Caution). Seismic: 2 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 3: Rain showers, 100% chance of rain. Max ~29°C. Aug 4: Thunderstorms, 100% chance of rain. Max ~27°C. Aug 5: Thunderstorms, 100% chance of rain. Max ~27°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-02-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-08-02T12:00:00+08:00",
      "title": "PH hazard brief — Aug 2, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Aug 2, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~34°C (Extreme Caution). Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Aug 2: Thunderstorms, 99% chance of rain. Max ~29°C. Aug 3: Rain showers, 98% chance of rain. Max ~28°C. Aug 4: Thunderstorms, 100% chance of rain. Max ~27°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-08-01-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-08-01T12:00:00+08:00",
      "title": "PH hazard brief — Aug 1, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Aug 1, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~38°C (Extreme Caution). Seismic: 3 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Aug 1: Thunderstorms, 100% chance of rain. Max ~31°C. Aug 2: Thunderstorms, 97% chance of rain. Max ~29°C. Aug 3: Thunderstorms, 100% chance of rain. Max ~28°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-31-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-31T12:00:00+08:00",
      "title": "PH hazard brief — Jul 31, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 31, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~36°C (Extreme Caution). Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Jul 31: Thunderstorms, 99% chance of rain. Max ~31°C. Aug 1: Rain showers, 100% chance of rain. Max ~31°C. Aug 2: Rain showers, 96% chance of rain. Max ~31°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-30-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-30T12:00:00+08:00",
      "title": "PH hazard brief — Jul 30, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 30, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~36°C (Extreme Caution). Seismic: 4 M4.0+ event(s) in the PH region (last 24h); nearest of note M5.1 ~211 km from Taguig (79 km NE of Casuguran, Philippines). 3-day outlook — Jul 30: Light drizzle, 46% chance of rain. Max ~31°C. Jul 31: Thunderstorms, 98% chance of rain. Max ~30°C. Aug 1: Thunderstorms, 100% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-29-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-29T12:00:00+08:00",
      "title": "PH hazard brief — Jul 29, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 29, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~27°C (Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 29: Thunderstorms, 98% chance of rain. Max ~26°C. Jul 30: Drizzle, 92% chance of rain. Max ~30°C. Jul 31: Thunderstorms, 99% chance of rain. Max ~31°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-28-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-28T12:00:00+08:00",
      "title": "PH hazard brief — Jul 28, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 28, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~38°C (Extreme Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 28: Thunderstorms, 100% chance of rain. Max ~32°C. Jul 29: Thunderstorms, 100% chance of rain. Max ~29°C. Jul 30: Thunderstorms, 100% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-27-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-27T12:00:00+08:00",
      "title": "PH hazard brief — Jul 27, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 27, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~36°C (Extreme Caution). Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Jul 27: Thunderstorms with hail, 75% chance of rain. Max ~31°C. Jul 28: Thunderstorms, 96% chance of rain. Max ~31°C. Jul 29: Thunderstorms, 96% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-26-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-26T12:00:00+08:00",
      "title": "PH hazard brief — Jul 26, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 26, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~35°C (Extreme Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 26: Thunderstorms, 80% chance of rain. Max ~30°C. Jul 27: Thunderstorms, 94% chance of rain. Max ~29°C. Jul 28: Thunderstorms, 92% chance of rain. Max ~31°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-25-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-07-25T12:00:00+08:00",
      "title": "PH hazard brief — Jul 25, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Jul 25, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~35°C (Extreme Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 25: Thunderstorms, 100% chance of rain. Max ~30°C. Jul 26: Thunderstorms, 97% chance of rain. Max ~29°C. Jul 27: Rain showers, 100% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-24-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-07-24T12:00:00+08:00",
      "title": "PH hazard brief — Jul 24, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Jul 24, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~34°C (Extreme Caution). Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Jul 24: Rain showers, 96% chance of rain. Max ~29°C. Jul 25: Thunderstorms, 100% chance of rain. Max ~29°C. Jul 26: Thunderstorms, 100% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-23-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-07-23T12:00:00+08:00",
      "title": "PH hazard brief — Jul 23, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Jul 23, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~38°C (Extreme Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 23: Thunderstorms, 100% chance of rain. Max ~33°C. Jul 24: Heavy drizzle, 98% chance of rain. Max ~29°C. Jul 25: Thunderstorms, 100% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-22-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-22T12:00:00+08:00",
      "title": "PH hazard brief — Jul 22, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 22, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~37°C (Extreme Caution). Seismic: 2 M4.0+ event(s) in the PH region (last 24h); nearest of note M4.6 ~242 km from Taguig (18 km SSE of Talisay, Philippines). 3-day outlook — Jul 22: Rain showers, 87% chance of rain. Max ~33°C. Jul 23: Rain showers, 99% chance of rain. Max ~32°C. Jul 24: Rain showers, 92% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    }
  ]
};
