/* Auto-generated by the cloud monitor (GitHub Actions). Do not edit by hand. */
window.PBCA_FEED = {
  "app": "PH Business Continuity Advisory",
  "client": "mySMB.com",
  "location": "BGC, Taguig City, Metro Manila",
  "generated_at": "2026-07-22T11:00:00+08:00",
  "current": {
    "tier": 1,
    "tier_label": "MONITOR",
    "action_needed": false,
    "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
    "headline": "Calm — no active cyclone, no NCR quakes.",
    "confidence": "MEDIUM",
    "next_update": "Automated hourly; full brief at 12:00 NN (Asia/Manila)",
    "monitoring_degraded": false,
    "degraded_note": "Volcano (PHIVOLCS) and dam levels are not yet in the automated cloud version — confirm those on the official sites if relevant.",
    "outlook_3day": [
      {
        "date": "Jul 22",
        "summary": "Rain showers, 87% chance of rain. Max ~33°C."
      },
      {
        "date": "Jul 23",
        "summary": "Rain showers, 99% chance of rain. Max ~32°C."
      },
      {
        "date": "Jul 24",
        "summary": "Rain showers, 92% chance of rain. Max ~30°C."
      }
    ],
    "weather": "No active tropical cyclone within the Philippine Area of Responsibility. Rain showers in Metro Manila; max ~33°C.",
    "heat_index": {
      "max_c": 37,
      "category": "Extreme Caution",
      "note": "Computed from Open-Meteo temperature and humidity for Metro Manila."
    },
    "volcanoes": [],
    "seismic_24h": {
      "count": 2,
      "ncr_relevant": false,
      "note": "2 M4.0+ event(s) in the PH region (last 24h); nearest of note M4.6 ~242 km from Taguig (18 km SSE of Talisay, Philippines)."
    },
    "dams": [],
    "sources": [
      {
        "label": "PAGASA — Tropical Cyclone Bulletin",
        "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
      },
      {
        "label": "PAGASA — Weather / Heat Index",
        "url": "https://www.pagasa.dost.gov.ph/weather/heat-index"
      },
      {
        "label": "PAGASA — Flood / Dam",
        "url": "https://www.pagasa.dost.gov.ph/flood"
      },
      {
        "label": "USGS — Earthquakes",
        "url": "https://earthquake.usgs.gov/earthquakes/map/"
      },
      {
        "label": "PHIVOLCS",
        "url": "https://www.phivolcs.dost.gov.ph/"
      }
    ]
  },
  "notifications": [
    {
      "id": "2026-07-21-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-21T12:00:00+08:00",
      "title": "PH hazard brief — Jul 21, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 21, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~38°C (Extreme Caution). Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Jul 21: Thunderstorms, 100% chance of rain. Max ~33°C. Jul 22: Heavy drizzle, 99% chance of rain. Max ~32°C. Jul 23: Thunderstorms, 100% chance of rain. Max ~32°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-20-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-20T12:00:00+08:00",
      "title": "PH hazard brief — Jul 20, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 20, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~37°C (Extreme Caution). Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Jul 20: Rain showers, 88% chance of rain. Max ~32°C. Jul 21: Rain showers, 100% chance of rain. Max ~31°C. Jul 22: Thunderstorms, 94% chance of rain. Max ~31°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-19-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-19T12:00:00+08:00",
      "title": "PH hazard brief — Jul 19, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 19, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~37°C (Extreme Caution). Seismic: No M4.0+ earthquakes in the PH region in the last 24h. 3-day outlook — Jul 19: Rain showers, 75% chance of rain. Max ~32°C. Jul 20: Thunderstorms, 98% chance of rain. Max ~32°C. Jul 21: Thunderstorms with hail, 99% chance of rain. Max ~31°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-18-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-18T12:00:00+08:00",
      "title": "PH hazard brief — Jul 18, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 18, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~37°C (Extreme Caution). Seismic: 3 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 18: Light drizzle, 67% chance of rain. Max ~32°C. Jul 19: Heavy drizzle, 80% chance of rain. Max ~31°C. Jul 20: Rain showers, 88% chance of rain. Max ~31°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-17-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-17T12:00:00+08:00",
      "title": "PH hazard brief — Jul 17, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 17, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~37°C (Extreme Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 17: Light drizzle, 31% chance of rain. Max ~32°C. Jul 18: Drizzle, 75% chance of rain. Max ~31°C. Jul 19: Thunderstorms, 84% chance of rain. Max ~31°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-16-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-16T12:00:00+08:00",
      "title": "PH hazard brief — Jul 16, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 16, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~37°C (Extreme Caution). Seismic: 2 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 16: Light drizzle, 16% chance of rain. Max ~32°C. Jul 17: Thunderstorms, 49% chance of rain. Max ~31°C. Jul 18: Rain showers, 77% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-15-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-15T12:00:00+08:00",
      "title": "PH hazard brief — Jul 15, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 15, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~37°C (Extreme Caution). Seismic: 4 M4.0+ event(s) in the PH region (last 24h); nearest of note M5.2 ~296 km from Taguig (14 km WSW of Mabiton, Philippines). 3-day outlook — Jul 15: Cloudy, 4% chance of rain. Max ~31°C. Jul 16: Light drizzle, 57% chance of rain. Max ~32°C. Jul 17: Thunderstorms, 67% chance of rain. Max ~32°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-14-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-07-14T12:00:00+08:00",
      "title": "PH hazard brief — Jul 14, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Jul 14, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~36°C (Extreme Caution). Seismic: 3 M4.0+ event(s) in the PH region (last 24h); nearest of note M4.6 ~254 km from Taguig (6 km NW of San Rafael, Philippines). 3-day outlook — Jul 14: Light drizzle, 59% chance of rain. Max ~31°C. Jul 15: Light drizzle, 61% chance of rain. Max ~31°C. Jul 16: Thunderstorms, 73% chance of rain. Max ~31°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-13-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-13T12:00:00+08:00",
      "title": "PH hazard brief — Jul 13, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 13, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~35°C (Extreme Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); nearest of note M5.4 ~289 km from Taguig (24 km W of Mabiton, Philippines). 3-day outlook — Jul 13: Rain showers, 99% chance of rain. Max ~30°C. Jul 14: Thunderstorms, 62% chance of rain. Max ~31°C. Jul 15: Thunderstorms, 50% chance of rain. Max ~31°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-12-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-12T12:00:00+08:00",
      "title": "PH hazard brief — Jul 12, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 12, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~34°C (Extreme Caution). Seismic: 2 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 12: Thunderstorms, 100% chance of rain. Max ~29°C. Jul 13: Thunderstorms, 98% chance of rain. Max ~29°C. Jul 14: Thunderstorms, 88% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-11-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-07-11T12:00:00+08:00",
      "title": "PH hazard brief — Jul 11, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Jul 11, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~33°C (Extreme Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 11: Thunderstorms, 99% chance of rain. Max ~29°C. Jul 12: Thunderstorms, 96% chance of rain. Max ~29°C. Jul 13: Thunderstorms, 90% chance of rain. Max ~29°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-10-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-07-10T12:00:00+08:00",
      "title": "PH hazard brief — Jul 10, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Jul 10, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~35°C (Extreme Caution). Seismic: 2 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 10: Heavy drizzle, 98% chance of rain. Max ~30°C. Jul 11: Thunderstorms, 100% chance of rain. Max ~29°C. Jul 12: Thunderstorms, 96% chance of rain. Max ~29°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-09-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-07-09T12:00:00+08:00",
      "title": "PH hazard brief — Jul 9, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Jul 9, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "Active tropical cyclone in PAR — confirm wind signal over Metro Manila on the official bulletin. Heat index today ~37°C (Extreme Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 9: Heavy drizzle, 84% chance of rain. Max ~31°C. Jul 10: Thunderstorms, 99% chance of rain. Max ~30°C. Jul 11: Thunderstorms, 100% chance of rain. Max ~28°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-08-digest",
      "type": "digest",
      "tier": 2,
      "tier_label": "PREPARE",
      "timestamp": "2026-07-08T12:00:00+08:00",
      "title": "PH hazard brief — Jul 8, 2026 — PREPARE",
      "bottom_line": "BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin.",
      "sms": "MYSMB brief Jul 8, 2026: BGC/Taguig: No action needed yet — review contingencies and watch the next bulletin. 3-day + heat index in the app.",
      "body": "M4.5 quake ~93 km from Taguig — may be felt in NCR. Heat index today ~38°C (Extreme Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); nearest of note M4.5 ~93 km from Taguig (7 km SSE of Calatagan, Philippines). 3-day outlook — Jul 8: Drizzle, 97% chance of rain. Max ~32°C. Jul 9: Thunderstorms, 75% chance of rain. Max ~31°C. Jul 10: Thunderstorms, 98% chance of rain. Max ~30°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-07-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-07T12:00:00+08:00",
      "title": "PH hazard brief — Jul 7, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "sms": "MYSMB brief Jul 7, 2026: BGC/Taguig: No action needed today. Normal operations. 3-day + heat index in the app.",
      "body": "Calm — no active cyclone, no NCR quakes. Heat index today ~38°C (Extreme Caution). Seismic: 1 M4.0+ event(s) in the PH region (last 24h); none near Metro Manila. 3-day outlook — Jul 7: Thunderstorms, 100% chance of rain. Max ~33°C. Jul 8: Heavy drizzle, 93% chance of rain. Max ~32°C. Jul 9: Drizzle, 71% chance of rain. Max ~31°C.",
      "sources": [
        {
          "label": "PAGASA — Tropical Cyclone Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-06-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-06T12:00:00+08:00",
      "title": "PH hazard brief — Jul 6, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "body": "No active tropical cyclone in PAR; no wind signal over Metro Manila. No NCR-relevant earthquakes — recent activity is confined to Mindanao, offshore Pangasinan, and Surigao; no M6.0+ within 150 km of Taguig; nothing felt in NCR. Dams normal: Angat 169.86 m (~40 m below spilling) and NCR/Pasig-Marikina-Laguna on Non-Flood Watch (8:00 AM reading). Volcano alert levels unverified today (PHIVOLCS not queried; assumed AL1). 3-day outlook: Jul 6 partly cloudy, isolated afternoon rains, no signals; Jul 7 isolated thunderstorms possible; Jul 8 partly cloudy, isolated rains/thunderstorms. Note: monitoring partially degraded — USGS seismic feed frozen ~4 days (metadata Jul 2); PAGASA TC and dam pages current, forecast/heat pages cached.",
      "sms": "MYSMB brief Jul6: BGC/Taguig no action needed. 3-day: isolated afternoon rain/thunderstorms, no signals. Dams normal. Full note via email.",
      "sources": [
        {
          "label": "PAGASA TC Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-05-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-05T12:00:00+08:00",
      "title": "PH hazard brief — Jul 5, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "body": "No active tropical cyclone in PAR; no wind signal over Metro Manila. No NCR-relevant earthquakes — recent activity is confined to Mindanao, offshore Pangasinan, and Surigao; no M6.0+ within 150 km of Taguig. Dams normal per last verified reading. Volcano alert levels unverified today (PHIVOLCS unreachable; assumed AL1). 3-day outlook: Jul 5 partly cloudy, isolated afternoon rains, no signals; Jul 6 isolated rains/thunderstorms possible; Jul 7 partly cloudy, isolated thunderstorms. Note: monitoring partially degraded — USGS frozen ~3 days, PAGASA forecast/heat pages cached, PHIVOLCS down.",
      "sms": "MYSMB brief Jul5: BGC/Taguig no action needed. 3-day: isolated rain/thunderstorms, no signals. Full note via email.",
      "sources": [
        {
          "label": "PAGASA TC Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-04-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-04T12:00:00+08:00",
      "title": "PH hazard brief — Jul 4, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed today. Normal operations.",
      "body": "No active tropical cyclone in PAR; no signal over Metro Manila. No M4.0+ quakes in the last 24h and nothing felt in NCR. Dams on Non-Flood Watch. Volcano alert levels unverified today (PHIVOLCS unreachable). 3-day outlook: Jul 5 scattered rains, no signals; Jul 6 possible afternoon monsoon rains; Jul 7 isolated thunderstorms. Note: monitoring partially degraded — USGS/PAGASA cached, PHIVOLCS down.",
      "sms": "MYSMB brief Jul4: BGC/Taguig no action needed. 3-day: light rain, no signals. Full note via email.",
      "sources": [
        {
          "label": "PAGASA TC Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    },
    {
      "id": "2026-07-03-digest",
      "type": "digest",
      "tier": 1,
      "tier_label": "MONITOR",
      "timestamp": "2026-07-03T12:00:00+08:00",
      "title": "PH hazard brief — Jul 3, 2026 — No action",
      "bottom_line": "BGC/Taguig: No action needed. Former TC Henry has exited PAR.",
      "body": "Former Typhoon Henry has left the Philippine Area of Responsibility; all wind signals lifted. Normal operations. No NCR-relevant seismic activity. Dams normal.",
      "sms": "MYSMB brief Jul3: BGC/Taguig no action. Henry has exited PAR, signals lifted. Full note via email.",
      "sources": [
        {
          "label": "PAGASA TC Bulletin",
          "url": "https://www.pagasa.dost.gov.ph/tropical-cyclone/severe-weather-bulletin"
        }
      ]
    }
  ]
};
